### ISSUE TITLE
Penyakit e

### ISSUE THREAD

**Issue by fsodic** [fsodic/FS-Loh-Iki#1]
Penykite 

```
05/22 16:14:37: Launching 'app' on Physical Device.
App restart successful without requiring a re-install.
$ adb shell am start -n "com.fastfun.tetris/org.cocos2dx.cpp.AppActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 1285 on device 'samsung-sm_g935f-9885e647554f505841'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application com.fastfun.tetris can be debugged on port 8100...
I/zygote64: no shared libraies, dex_files: 1
W/ResourceType: ResTable_typeSpec entry count inconsistent: given 67, previously 69
    ResTable_typeSpec entry count inconsistent: given 5678, previously 5679
    ResTable_typeSpec entry count inconsistent: given 67, previously 69
W/ResourceType: ResTable_typeSpec entry count inconsistent: given 5678, previously 5679
I/zygote64: Do partial code cache collection, code=29KB, data=21KB
I/zygote64: After code cache collection, code=29KB, data=21KB
I/zygote64: Increasing code cache capacity to 128KB
D/main: cocos_android_app_init
D/Cocos2dxHelper: isSupportLowLatency:false
D/Cocos2dxHelper: sampleRate: 48000, framesPerBuffer: 240
D/Java_org_cocos2dx_lib_Cocos2dxHelper.cpp: nativeSetAudioDeviceInfo: sampleRate: 48000, bufferSizeInFrames: 240
W/zygote64: Class com.google.android.gms.dynamite.DynamiteModule failed lock verification and will run slower.
    Common causes for lock verification issues are non-optimized dex code
    and incorrect proguard optimizations.
D/EngineDataManager.cpp: nativeSetSupportOptimization: 0
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fastfun.tetris, PID: 1285
    java.lang.VerifyError: Verifier rejected class com.google.android.gms.games.b$a: int com.google.android.gms.games.b$a.hashCode() failed to verify: int com.google.android.gms.games.b$a.hashCode(): [0x4] 'this' argument 'Uninitialized Reference: java.lang.RuntimeException Allocation PC: 0' not instance of 'Reference: java.lang.Runtime' (declaration of 'com.google.android.gms.games.b$a' appears in /data/app/com.fastfun.tetris-PFqtqlk4M1nv4JTxk_0-lQ==/base.apk)
        at com.google.android.gms.games.b$a.b(Unknown Source:0)
        at com.RoyalGame.tools.GameHelper.<init>(Unknown Source:19)
        at org.cocos2dx.cpp.AppActivity.onCreate(Unknown Source:10)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
W/zygote64: Skipping duplicate class check due to unrecognized classloader
W/DynamiteModule: Local module descriptor class for com.google.android.gms.measurement.dynamite not found.
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:210890500
    Selected remote version of com.google.android.gms.ads.dynamite, version >= 210890500
V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
W/DynamiteModule: Failed to load remote module: Failed to load remote module.
W/Ads: #007 Could not call remote method. @7
    com.google.android.gms.internal.ads.Wl: com.google.android.gms.internal.ads.Wl: com.google.android.gms.dynamite.DynamiteModule$a: Remote load failed. No local fallback found.
        at com.google.android.gms.internal.ads.Tl.a(Unknown Source:16)
        at com.google.android.gms.internal.ads.gf.a(Unknown Source:4)
        at com.google.android.gms.internal.ads.gf.b(Unknown Source:37)
        at com.google.android.gms.internal.ads.ff.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.gms.internal.ads.Wl: com.google.android.gms.dynamite.DynamiteModule$a: Remote load failed. No local fallback found.
        at com.google.android.gms.internal.ads.Tl.b(Unknown Source:12)
        at com.google.android.gms.internal.ads.Tl.a(Unknown Source:0)
        at com.google.android.gms.internal.ads.gf.a(Unknown Source:4) 
        at com.google.android.gms.internal.ads.gf.b(Unknown Source:37) 
        at com.google.android.gms.internal.ads.ff.run(Unknown Source:4) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: com.google.android.gms.dynamite.DynamiteModule$a: Remote load failed. No local fallback found.
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:211)
        at com.google.android.gms.internal.ads.Tl.b(Unknown Source:4)
        at com.google.android.gms.internal.ads.Tl.a(Unknown Source:0) 
        at com.google.android.gms.internal.ads.gf.a(Unknown Source:4) 
        at com.google.android.gms.internal.ads.gf.b(Unknown Source:37) 
        at com.google.android.gms.internal.ads.ff.run(Unknown Source:4) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: com.google.android.gms.dynamite.DynamiteModule$a: Failed to load remote module.
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:150)
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:131)
        at com.google.android.gms.internal.ads.Tl.b(Unknown Source:4) 
        at com.google.android.gms.internal.ads.Tl.a(Unknown Source:0) 
        at com.google.android.gms.internal.ads.gf.a(Unknown Source:4) 
        at com.google.android.gms.internal.ads.gf.b(Unknown Source:37) 
        at com.google.android.gms.internal.ads.ff.run(Unknown Source:4) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.VerifyError: Verifier rejected class b.c.b.a.d.c.c: void b.c.b.a.d.c.c.a(android.os.Parcel, boolean) failed to verify: void b.c.b.a.d.c.c.a(android.os.Parcel, boolean): [0x4] 'this' argument 'Uninitialized Reference: java.lang.RuntimeException Allocation PC: 0' not instance of 'Reference: java.lang.Runtime' (declaration of 'b.c.b.a.d.c.c' appears in /data/app/com.fastfun.tetris-PFqtqlk4M1nv4JTxk_0-lQ==/base.apk)
        at b.c.b.a.d.c.c.a(Unknown Source:0)
        at com.google.android.gms.dynamite.l.b(Unknown Source:4)
        at com.google.android.gms.dynamite.DynamiteModule.b(Unknown Source:97)
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:15)
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:131) 
        at com.google.android.gms.internal.ads.Tl.b(Unknown Source:4) 
        at com.google.android.gms.internal.ads.Tl.a(Unknown Source:0) 
        at com.google.android.gms.internal.ads.gf.a(Unknown Source:4) 
        at com.google.android.gms.internal.ads.gf.b(Unknown Source:37) 
        at com.google.android.gms.internal.ads.ff.run(Unknown Source:4) 
        at java.lang.Thread.run(Thread.java:764) 
I/DynamiteModule: Considering local module com.google.android.gms.measurement.dynamite:0 and remote module com.google.android.gms.measurement.dynamite:49
I/DynamiteModule: Selected remote version of com.google.android.gms.measurement.dynamite, version >= 49
V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
I/zygote64: Rejecting re-init on previously-failed class java.lang.Class<b.c.b.a.d.c.c>: java.lang.VerifyError: Verifier rejected class b.c.b.a.d.c.c: void b.c.b.a.d.c.c.a(android.os.Parcel, boolean) failed to verify: void b.c.b.a.d.c.c.a(android.os.Parcel, boolean): [0x4] 'this' argument 'Uninitialized Reference: java.lang.RuntimeException Allocation PC: 0' not instance of 'Reference: java.lang.Runtime' (declaration of 'b.c.b.a.d.c.c' appears in /data/app/com.fastfun.tetris-PFqtqlk4M1nv4JTxk_0-lQ==/base.apk)
    (Throwable with no stack trace)
W/DynamiteModule: Failed to load remote module: Failed to load remote module.
W/FA-Ads: Data collection startup failed. No data will be collected.
    com.google.android.gms.dynamite.DynamiteModule$a: Remote load failed. No local fallback found.
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:211)
        at b.c.b.a.d.f.I.a(Unknown Source:9)
        at b.c.b.a.d.f.b.a(Unknown Source:67)
        at b.c.b.a.d.f.I$a.run(Unknown Source:12)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.gms.dynamite.DynamiteModule$a: Failed to load remote module.
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:150)
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:131)
        at b.c.b.a.d.f.I.a(Unknown Source:9) 
        at b.c.b.a.d.f.b.a(Unknown Source:67) 
        at b.c.b.a.d.f.I$a.run(Unknown Source:12) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.NoClassDefFoundError: b.c.b.a.d.c.c
        at b.c.b.a.d.c.c.a(Unknown Source:0)
        at com.google.android.gms.dynamite.l.b(Unknown Source:4)
        at com.google.android.gms.dynamite.DynamiteModule.b(Unknown Source:97)
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:15)
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:131) 
        at b.c.b.a.d.f.I.a(Unknown Source:9) 
        at b.c.b.a.d.f.b.a(Unknown Source:67) 
        at b.c.b.a.d.f.I$a.run(Unknown Source:12) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.VerifyError: Verifier rejected class b.c.b.a.d.c.c: void b.c.b.a.d.c.c.a(android.os.Parcel, boolean) failed to verify: void b.c.b.a.d.c.c.a(android.os.Parcel, boolean): [0x4] 'this' argument 'Uninitialized Reference: java.lang.RuntimeException Allocation PC: 0' not instance of 'Reference: java.lang.Runtime' (declaration of 'b.c.b.a.d.c.c' appears in /data/app/com.fastfun.tetris-PFqtqlk4M1nv4JTxk_0-lQ==/base.apk)
        at b.c.b.a.d.c.c.a(Unknown Source:0)
        at com.google.android.gms.dynamite.l.b(Unknown Source:4)
        at com.google.android.gms.dynamite.DynamiteModule.b(Unknown Source:97)
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:15)
        at com.google.android.gms.dynamite.DynamiteModule.a(Unknown Source:131)
        at com.google.android.gms.internal.ads.Tl.b(Unknown Source:4)
        at com.google.android.gms.internal.ads.Tl.a(Unknown Source:0)
        at com.google.android.gms.internal.ads.gf.a(Unknown Source:4)
        at com.google.android.gms.internal.ads.gf.b(Unknown Source:37)
        at com.google.android.gms.internal.ads.ff.run(Unknown Source:4)
        at java.lang.Thread.run(Thread.java:764) 
    Failed to connect to measurement client.
I/zygote64: WaitForGcToComplete blocked for 13.871ms for cause HeapTrim
```

Penyakit akut:
```
java.lang.VerifyError: Verifier rejected class com.google.android.gms.games.b$a: int com.google.android.gms.games.b$a.hashCode() failed to verify: int com.google.android.gms.games.b$a.hashCode(): [0x4] 'this' argument 'Uninitialized Reference: java.lang.RuntimeException Allocation PC: 0' not instance of 'Reference: java.lang.Runtime' (declaration of 'com.google.android.gms.games.b$a' appears in /data/app/com.fastfun.tetris-PFqtqlk4M1nv4JTxk_0-lQ==/base.apk)
```

**Comment by fsodic** [comment]
Update jar
